name: documentation

on:
  pull_request:
    branches: [docs]
  push:
    branches: [docs]
  workflow_dispatch:
    branches: [docs]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: docs
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: docs
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.LAUNDRO_DOCS_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "shen_yi_hong@outlook.com"
          git config --global user.name "shenyih0ng"
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run deploy
